ipython operate_cla.py $CLA_ROOT/corpus/tidigits_flac/data/adults/train/man/aj/2a.spc $CLA_ROOT/memory/20150826_02.cla
ipython operate_cla.py $CLA_ROOT/corpus/tidigits_flac/data/adults/train/man/aj/2a.spc $CLA_ROOT/memory/20150826_02.cla

ipython operate_cla.py $CLA_ROOT/corpus/tidigits_flac/data/adults/train/man/aj/2a.spc $CLA_ROOT/memory/20150826_02.cla
ipython operate_cla.py $CLA_ROOT/corpus/tidigits_flac/data/adults/train/man/aj/2a.spc $CLA_ROOT/memory/20150826_02.cla
ipython operate_cla.py $CLA_ROOT/corpus/tidigits_flac/data/adults/train/man/aj/2a.spc $CLA_ROOT/memory/20150826_02.cla
ipython operate_cla.py $CLA_ROOT/corpus/tidigits_flac/data/adults/train/man/aj/2a.spc $CLA_ROOT/memory/20150826_02.cla
ipython operate_cla.py $CLA_ROOT/corpus/tidigits_flac/data/adults/train/man/aj/2a.spc $CLA_ROOT/memory/20150826_02.cla
ipython operate_cla.py $CLA_ROOT/corpus/tidigits_flac/data/adults/train/man/aj/2a.spc $CLA_ROOT/memory/20150826_02.cla
ipython operate_cla.py $CLA_ROOT/corpus/tidigits_flac/data/adults/train/man/aj/2a.spc $CLA_ROOT/memory/20150826_02.cla
ipython operate_cla.py $CLA_ROOT/corpus/tidigits_flac/data/adults/train/man/aj/2a.spc $CLA_ROOT/memory/20150826_02.cla
ipython operate_cla.py $CLA_ROOT/corpus/tidigits_flac/data/adults/train/man/aj/2a.spc $CLA_ROOT/memory/20150826_02.cla
ipython operate_cla.py $CLA_ROOT/corpus/tidigits_flac/data/adults/train/man/aj/2a.spc $CLA_ROOT/memory/20150826_02.cla
ipython operate_cla.py $CLA_ROOT/corpus/tidigits_flac/data/adults/train/man/aj/2a.spc $CLA_ROOT/memory/20150826_02.cla
ipython operate_cla.py $CLA_ROOT/corpus/tidigits_flac/data/adults/train/man/aj/2a.spc $CLA_ROOT/memory/20150826_02.cla
ipython operate_cla.py $CLA_ROOT/corpus/tidigits_flac/data/adults/train/man/aj/2a.spc $CLA_ROOT/memory/20150826_02.cla
ipython operate_cla.py $CLA_ROOT/corpus/tidigits_flac/data/adults/train/man/aj/2a.spc $CLA_ROOT/memory/20150826_02.cla
ipython operate_cla.py $CLA_ROOT/corpus/tidigits_flac/data/adults/train/man/aj/2a.spc $CLA_ROOT/memory/20150826_02.cla
ipython operate_cla.py $CLA_ROOT/corpus/tidigits_flac/data/adults/train/man/aj/2a.spc $CLA_ROOT/memory/20150826_02.cla
ipython operate_cla.py $CLA_ROOT/corpus/tidigits_flac/data/adults/train/man/aj/2a.spc $CLA_ROOT/memory/20150826_02.cla
ipython operate_cla.py $CLA_ROOT/corpus/tidigits_flac/data/adults/train/man/aj/2a.spc $CLA_ROOT/memory/20150826_02.cla
ipython operate_cla.py $CLA_ROOT/corpus/tidigits_flac/data/adults/train/man/aj/2a.spc $CLA_ROOT/memory/20150826_02.cla
ipython operate_cla.py $CLA_ROOT/corpus/tidigits_flac/data/adults/train/man/aj/2a.spc $CLA_ROOT/memory/20150826_02.cla
ipython operate_cla.py $CLA_ROOT/corpus/tidigits_flac/data/adults/train/man/aj/2a.spc $CLA_ROOT/memory/20150826_02.cla
ipython operate_cla.py $CLA_ROOT/corpus/tidigits_flac/data/adults/train/man/aj/2a.spc $CLA_ROOT/memory/20150826_02.cla
ipython operate_cla.py $CLA_ROOT/corpus/tidigits_flac/data/adults/train/man/aj/2a.spc $CLA_ROOT/memory/20150826_02.cla
ipython operate_cla.py $CLA_ROOT/corpus/tidigits_flac/data/adults/train/man/aj/2a.spc $CLA_ROOT/memory/20150826_02.cla
ipython operate_cla.py $CLA_ROOT/corpus/tidigits_flac/data/adults/train/man/aj/2a.spc $CLA_ROOT/memory/20150826_02.cla
ipython operate_cla.py $CLA_ROOT/corpus/tidigits_flac/data/adults/train/man/aj/2a.spc $CLA_ROOT/memory/20150826_02.cla
ipython operate_cla.py $CLA_ROOT/corpus/tidigits_flac/data/adults/train/man/aj/2a.spc $CLA_ROOT/memory/20150826_02.cla
ipython operate_cla.py $CLA_ROOT/corpus/tidigits_flac/data/adults/train/man/aj/2a.spc $CLA_ROOT/memory/20150826_02.cla
ipython operate_cla.py $CLA_ROOT/corpus/tidigits_flac/data/adults/train/man/aj/2a.spc $CLA_ROOT/memory/20150826_02.cla
ipython operate_cla.py $CLA_ROOT/corpus/tidigits_flac/data/adults/train/man/aj/2a.spc $CLA_ROOT/memory/20150826_02.cla
ipython operate_cla.py $CLA_ROOT/corpus/tidigits_flac/data/adults/train/man/aj/2a.spc $CLA_ROOT/memory/20150826_02.cla
ipython operate_cla.py $CLA_ROOT/corpus/tidigits_flac/data/adults/train/man/aj/2a.spc $CLA_ROOT/memory/20150826_02.cla
ipython operate_cla.py $CLA_ROOT/corpus/tidigits_flac/data/adults/train/man/aj/2a.spc $CLA_ROOT/memory/20150826_02.cla
ipython operate_cla.py $CLA_ROOT/corpus/tidigits_flac/data/adults/train/man/aj/2a.spc $CLA_ROOT/memory/20150826_02.cla
ipython operate_cla.py $CLA_ROOT/corpus/tidigits_flac/data/adults/train/man/aj/2a.spc $CLA_ROOT/memory/20150826_02.cla
ipython operate_cla.py $CLA_ROOT/corpus/tidigits_flac/data/adults/train/man/aj/2a.spc $CLA_ROOT/memory/20150826_02.cla
ipython operate_cla.py $CLA_ROOT/corpus/tidigits_flac/data/adults/train/man/aj/2a.spc $CLA_ROOT/memory/20150826_02.cla
ipython operate_cla.py $CLA_ROOT/corpus/tidigits_flac/data/adults/train/man/aj/2a.spc $CLA_ROOT/memory/20150826_02.cla
ipython operate_cla.py $CLA_ROOT/corpus/tidigits_flac/data/adults/train/man/aj/2a.spc $CLA_ROOT/memory/20150826_02.cla
ipython operate_cla.py $CLA_ROOT/corpus/tidigits_flac/data/adults/train/man/aj/2a.spc $CLA_ROOT/memory/20150826_02.cla
ipython operate_cla.py $CLA_ROOT/corpus/tidigits_flac/data/adults/train/man/aj/2a.spc $CLA_ROOT/memory/20150826_02.cla
ipython operate_cla.py $CLA_ROOT/corpus/tidigits_flac/data/adults/train/man/aj/2a.spc $CLA_ROOT/memory/20150826_02.cla
ipython operate_cla.py $CLA_ROOT/corpus/tidigits_flac/data/adults/train/man/aj/2a.spc $CLA_ROOT/memory/20150826_02.cla
ipython operate_cla.py $CLA_ROOT/corpus/tidigits_flac/data/adults/train/man/aj/2a.spc $CLA_ROOT/memory/20150826_02.cla
ipython operate_cla.py $CLA_ROOT/corpus/tidigits_flac/data/adults/train/man/aj/2a.spc $CLA_ROOT/memory/20150826_02.cla
ipython operate_cla.py $CLA_ROOT/corpus/tidigits_flac/data/adults/train/man/aj/2a.spc $CLA_ROOT/memory/20150826_02.cla
ipython operate_cla.py $CLA_ROOT/corpus/tidigits_flac/data/adults/train/man/aj/2a.spc $CLA_ROOT/memory/20150826_02.cla
ipython operate_cla.py $CLA_ROOT/corpus/tidigits_flac/data/adults/train/man/aj/2a.spc $CLA_ROOT/memory/20150826_02.cla
ipython operate_cla.py $CLA_ROOT/corpus/tidigits_flac/data/adults/train/man/aj/2a.spc $CLA_ROOT/memory/20150826_02.cla
ipython operate_cla.py $CLA_ROOT/corpus/tidigits_flac/data/adults/train/man/aj/2a.spc $CLA_ROOT/memory/20150826_02.cla
ipython operate_cla.py $CLA_ROOT/corpus/tidigits_flac/data/adults/train/man/aj/2a.spc $CLA_ROOT/memory/20150826_02.cla
ipython operate_cla.py $CLA_ROOT/corpus/tidigits_flac/data/adults/train/man/aj/2a.spc $CLA_ROOT/memory/20150826_02.cla
ipython operate_cla.py $CLA_ROOT/corpus/tidigits_flac/data/adults/train/man/aj/2a.spc $CLA_ROOT/memory/20150826_02.cla
ipython operate_cla.py $CLA_ROOT/corpus/tidigits_flac/data/adults/train/man/aj/2a.spc $CLA_ROOT/memory/20150826_02.cla
ipython operate_cla.py $CLA_ROOT/corpus/tidigits_flac/data/adults/train/man/aj/2a.spc $CLA_ROOT/memory/20150826_02.cla
ipython operate_cla.py $CLA_ROOT/corpus/tidigits_flac/data/adults/train/man/aj/2a.spc $CLA_ROOT/memory/20150826_02.cla
ipython operate_cla.py $CLA_ROOT/corpus/tidigits_flac/data/adults/train/man/aj/2a.spc $CLA_ROOT/memory/20150826_02.cla
ipython operate_cla.py $CLA_ROOT/corpus/tidigits_flac/data/adults/train/man/aj/2a.spc $CLA_ROOT/memory/20150826_02.cla
ipython operate_cla.py $CLA_ROOT/corpus/tidigits_flac/data/adults/train/man/aj/2a.spc $CLA_ROOT/memory/20150826_02.cla
ipython operate_cla.py $CLA_ROOT/corpus/tidigits_flac/data/adults/train/man/aj/2a.spc $CLA_ROOT/memory/20150826_02.cla
ipython operate_cla.py $CLA_ROOT/corpus/tidigits_flac/data/adults/train/man/aj/2a.spc $CLA_ROOT/memory/20150826_02.cla
ipython operate_cla.py $CLA_ROOT/corpus/tidigits_flac/data/adults/train/man/aj/2a.spc $CLA_ROOT/memory/20150826_02.cla
ipython operate_cla.py $CLA_ROOT/corpus/tidigits_flac/data/adults/train/man/aj/2a.spc $CLA_ROOT/memory/20150826_02.cla
ipython operate_cla.py $CLA_ROOT/corpus/tidigits_flac/data/adults/train/man/aj/2a.spc $CLA_ROOT/memory/20150826_02.cla
ipython operate_cla.py $CLA_ROOT/corpus/tidigits_flac/data/adults/train/man/aj/2a.spc $CLA_ROOT/memory/20150826_02.cla
ipython operate_cla.py $CLA_ROOT/corpus/tidigits_flac/data/adults/train/man/aj/2a.spc $CLA_ROOT/memory/20150826_02.cla
ipython operate_cla.py $CLA_ROOT/corpus/tidigits_flac/data/adults/train/man/aj/2a.spc $CLA_ROOT/memory/20150826_02.cla
ipython operate_cla.py $CLA_ROOT/corpus/tidigits_flac/data/adults/train/man/aj/2a.spc $CLA_ROOT/memory/20150826_02.cla
ipython operate_cla.py $CLA_ROOT/corpus/tidigits_flac/data/adults/train/man/aj/2a.spc $CLA_ROOT/memory/20150826_02.cla
ipython operate_cla.py $CLA_ROOT/corpus/tidigits_flac/data/adults/train/man/aj/2a.spc $CLA_ROOT/memory/20150826_02.cla
ipython operate_cla.py $CLA_ROOT/corpus/tidigits_flac/data/adults/train/man/aj/2a.spc $CLA_ROOT/memory/20150826_02.cla
ipython operate_cla.py $CLA_ROOT/corpus/tidigits_flac/data/adults/train/man/aj/2a.spc $CLA_ROOT/memory/20150826_02.cla
ipython operate_cla.py $CLA_ROOT/corpus/tidigits_flac/data/adults/train/man/aj/2a.spc $CLA_ROOT/memory/20150826_02.cla
ipython operate_cla.py $CLA_ROOT/corpus/tidigits_flac/data/adults/train/man/aj/2a.spc $CLA_ROOT/memory/20150826_02.cla
ipython operate_cla.py $CLA_ROOT/corpus/tidigits_flac/data/adults/train/man/aj/2a.spc $CLA_ROOT/memory/20150826_02.cla
ipython operate_cla.py $CLA_ROOT/corpus/tidigits_flac/data/adults/train/man/aj/2a.spc $CLA_ROOT/memory/20150826_02.cla
ipython operate_cla.py $CLA_ROOT/corpus/tidigits_flac/data/adults/train/man/aj/2a.spc $CLA_ROOT/memory/20150826_02.cla
ipython operate_cla.py $CLA_ROOT/corpus/tidigits_flac/data/adults/train/man/aj/2a.spc $CLA_ROOT/memory/20150826_02.cla
ipython operate_cla.py $CLA_ROOT/corpus/tidigits_flac/data/adults/train/man/aj/2a.spc $CLA_ROOT/memory/20150826_02.cla
ipython operate_cla.py $CLA_ROOT/corpus/tidigits_flac/data/adults/train/man/aj/2a.spc $CLA_ROOT/memory/20150826_02.cla
ipython operate_cla.py $CLA_ROOT/corpus/tidigits_flac/data/adults/train/man/aj/2a.spc $CLA_ROOT/memory/20150826_02.cla
ipython operate_cla.py $CLA_ROOT/corpus/tidigits_flac/data/adults/train/man/aj/2a.spc $CLA_ROOT/memory/20150826_02.cla
ipython operate_cla.py $CLA_ROOT/corpus/tidigits_flac/data/adults/train/man/aj/2a.spc $CLA_ROOT/memory/20150826_02.cla
ipython operate_cla.py $CLA_ROOT/corpus/tidigits_flac/data/adults/train/man/aj/2a.spc $CLA_ROOT/memory/20150826_02.cla
ipython operate_cla.py $CLA_ROOT/corpus/tidigits_flac/data/adults/train/man/aj/2a.spc $CLA_ROOT/memory/20150826_02.cla
ipython operate_cla.py $CLA_ROOT/corpus/tidigits_flac/data/adults/train/man/aj/2a.spc $CLA_ROOT/memory/20150826_02.cla
ipython operate_cla.py $CLA_ROOT/corpus/tidigits_flac/data/adults/train/man/aj/2a.spc $CLA_ROOT/memory/20150826_02.cla
ipython operate_cla.py $CLA_ROOT/corpus/tidigits_flac/data/adults/train/man/aj/2a.spc $CLA_ROOT/memory/20150826_02.cla
ipython operate_cla.py $CLA_ROOT/corpus/tidigits_flac/data/adults/train/man/aj/2a.spc $CLA_ROOT/memory/20150826_02.cla
ipython operate_cla.py $CLA_ROOT/corpus/tidigits_flac/data/adults/train/man/aj/2a.spc $CLA_ROOT/memory/20150826_02.cla
ipython operate_cla.py $CLA_ROOT/corpus/tidigits_flac/data/adults/train/man/aj/2a.spc $CLA_ROOT/memory/20150826_02.cla
ipython operate_cla.py $CLA_ROOT/corpus/tidigits_flac/data/adults/train/man/aj/2a.spc $CLA_ROOT/memory/20150826_02.cla
ipython operate_cla.py $CLA_ROOT/corpus/tidigits_flac/data/adults/train/man/aj/2a.spc $CLA_ROOT/memory/20150826_02.cla
ipython operate_cla.py $CLA_ROOT/corpus/tidigits_flac/data/adults/train/man/aj/2a.spc $CLA_ROOT/memory/20150826_02.cla
ipython operate_cla.py $CLA_ROOT/corpus/tidigits_flac/data/adults/train/man/aj/2a.spc $CLA_ROOT/memory/20150826_02.cla
ipython operate_cla.py $CLA_ROOT/corpus/tidigits_flac/data/adults/train/man/aj/2a.spc $CLA_ROOT/memory/20150826_02.cla
ipython operate_cla.py $CLA_ROOT/corpus/tidigits_flac/data/adults/train/man/aj/2a.spc $CLA_ROOT/memory/20150826_02.cla
ipython operate_cla.py $CLA_ROOT/corpus/tidigits_flac/data/adults/train/man/aj/2a.spc $CLA_ROOT/memory/20150826_02.cla
ipython operate_cla.py $CLA_ROOT/corpus/tidigits_flac/data/adults/train/man/aj/2a.spc $CLA_ROOT/memory/20150826_02.cla
ipython operate_cla.py $CLA_ROOT/corpus/tidigits_flac/data/adults/train/man/aj/2a.spc $CLA_ROOT/memory/20150826_02.cla
ipython operate_cla.py $CLA_ROOT/corpus/tidigits_flac/data/adults/train/man/aj/2a.spc $CLA_ROOT/memory/20150826_02.cla
ipython operate_cla.py $CLA_ROOT/corpus/tidigits_flac/data/adults/train/man/aj/2a.spc $CLA_ROOT/memory/20150826_02.cla
ipython operate_cla.py $CLA_ROOT/corpus/tidigits_flac/data/adults/train/man/aj/2a.spc $CLA_ROOT/memory/20150826_02.cla
ipython operate_cla.py $CLA_ROOT/corpus/tidigits_flac/data/adults/train/man/aj/2a.spc $CLA_ROOT/memory/20150826_02.cla
ipython operate_cla.py $CLA_ROOT/corpus/tidigits_flac/data/adults/train/man/aj/2a.spc $CLA_ROOT/memory/20150826_02.cla
ipython operate_cla.py $CLA_ROOT/corpus/tidigits_flac/data/adults/train/man/aj/2a.spc $CLA_ROOT/memory/20150826_02.cla
ipython operate_cla.py $CLA_ROOT/corpus/tidigits_flac/data/adults/train/man/aj/2a.spc $CLA_ROOT/memory/20150826_02.cla
ipython operate_cla.py $CLA_ROOT/corpus/tidigits_flac/data/adults/train/man/aj/2a.spc $CLA_ROOT/memory/20150826_02.cla
ipython operate_cla.py $CLA_ROOT/corpus/tidigits_flac/data/adults/train/man/aj/2a.spc $CLA_ROOT/memory/20150826_02.cla
ipython operate_cla.py $CLA_ROOT/corpus/tidigits_flac/data/adults/train/man/aj/2a.spc $CLA_ROOT/memory/20150826_02.cla
ipython operate_cla.py $CLA_ROOT/corpus/tidigits_flac/data/adults/train/man/aj/2a.spc $CLA_ROOT/memory/20150826_02.cla
ipython operate_cla.py $CLA_ROOT/corpus/tidigits_flac/data/adults/train/man/aj/2a.spc $CLA_ROOT/memory/20150826_02.cla
ipython operate_cla.py $CLA_ROOT/corpus/tidigits_flac/data/adults/train/man/aj/2a.spc $CLA_ROOT/memory/20150826_02.cla
ipython operate_cla.py $CLA_ROOT/corpus/tidigits_flac/data/adults/train/man/aj/2a.spc $CLA_ROOT/memory/20150826_02.cla
ipython operate_cla.py $CLA_ROOT/corpus/tidigits_flac/data/adults/train/man/aj/2a.spc $CLA_ROOT/memory/20150826_02.cla
ipython operate_cla.py $CLA_ROOT/corpus/tidigits_flac/data/adults/train/man/aj/2a.spc $CLA_ROOT/memory/20150826_02.cla
ipython operate_cla.py $CLA_ROOT/corpus/tidigits_flac/data/adults/train/man/aj/2a.spc $CLA_ROOT/memory/20150826_02.cla
ipython operate_cla.py $CLA_ROOT/corpus/tidigits_flac/data/adults/train/man/aj/2a.spc $CLA_ROOT/memory/20150826_02.cla
ipython operate_cla.py $CLA_ROOT/corpus/tidigits_flac/data/adults/train/man/aj/2a.spc $CLA_ROOT/memory/20150826_02.cla
ipython operate_cla.py $CLA_ROOT/corpus/tidigits_flac/data/adults/train/man/aj/2a.spc $CLA_ROOT/memory/20150826_02.cla
ipython operate_cla.py $CLA_ROOT/corpus/tidigits_flac/data/adults/train/man/aj/2a.spc $CLA_ROOT/memory/20150826_02.cla
ipython operate_cla.py $CLA_ROOT/corpus/tidigits_flac/data/adults/train/man/aj/2a.spc $CLA_ROOT/memory/20150826_02.cla
ipython operate_cla.py $CLA_ROOT/corpus/tidigits_flac/data/adults/train/man/aj/2a.spc $CLA_ROOT/memory/20150826_02.cla
ipython operate_cla.py $CLA_ROOT/corpus/tidigits_flac/data/adults/train/man/aj/2a.spc $CLA_ROOT/memory/20150826_02.cla
ipython operate_cla.py $CLA_ROOT/corpus/tidigits_flac/data/adults/train/man/aj/2a.spc $CLA_ROOT/memory/20150826_02.cla
ipython operate_cla.py $CLA_ROOT/corpus/tidigits_flac/data/adults/train/man/aj/2a.spc $CLA_ROOT/memory/20150826_02.cla
ipython operate_cla.py $CLA_ROOT/corpus/tidigits_flac/data/adults/train/man/aj/2a.spc $CLA_ROOT/memory/20150826_02.cla
ipython operate_cla.py $CLA_ROOT/corpus/tidigits_flac/data/adults/train/man/aj/2a.spc $CLA_ROOT/memory/20150826_02.cla
ipython operate_cla.py $CLA_ROOT/corpus/tidigits_flac/data/adults/train/man/aj/2a.spc $CLA_ROOT/memory/20150826_02.cla
ipython operate_cla.py $CLA_ROOT/corpus/tidigits_flac/data/adults/train/man/aj/2a.spc $CLA_ROOT/memory/20150826_02.cla
ipython operate_cla.py $CLA_ROOT/corpus/tidigits_flac/data/adults/train/man/aj/2a.spc $CLA_ROOT/memory/20150826_02.cla
ipython operate_cla.py $CLA_ROOT/corpus/tidigits_flac/data/adults/train/man/aj/2a.spc $CLA_ROOT/memory/20150826_02.cla
ipython operate_cla.py $CLA_ROOT/corpus/tidigits_flac/data/adults/train/man/aj/2a.spc $CLA_ROOT/memory/20150826_02.cla
ipython operate_cla.py $CLA_ROOT/corpus/tidigits_flac/data/adults/train/man/aj/2a.spc $CLA_ROOT/memory/20150826_02.cla
ipython operate_cla.py $CLA_ROOT/corpus/tidigits_flac/data/adults/train/man/aj/2a.spc $CLA_ROOT/memory/20150826_02.cla
ipython operate_cla.py $CLA_ROOT/corpus/tidigits_flac/data/adults/train/man/aj/2a.spc $CLA_ROOT/memory/20150826_02.cla
ipython operate_cla.py $CLA_ROOT/corpus/tidigits_flac/data/adults/train/man/aj/2a.spc $CLA_ROOT/memory/20150826_02.cla
ipython operate_cla.py $CLA_ROOT/corpus/tidigits_flac/data/adults/train/man/aj/2a.spc $CLA_ROOT/memory/20150826_02.cla
ipython operate_cla.py $CLA_ROOT/corpus/tidigits_flac/data/adults/train/man/aj/2a.spc $CLA_ROOT/memory/20150826_02.cla
ipython operate_cla.py $CLA_ROOT/corpus/tidigits_flac/data/adults/train/man/aj/2a.spc $CLA_ROOT/memory/20150826_02.cla
ipython operate_cla.py $CLA_ROOT/corpus/tidigits_flac/data/adults/train/man/aj/2a.spc $CLA_ROOT/memory/20150826_02.cla
ipython operate_cla.py $CLA_ROOT/corpus/tidigits_flac/data/adults/train/man/aj/2a.spc $CLA_ROOT/memory/20150826_02.cla
ipython operate_cla.py $CLA_ROOT/corpus/tidigits_flac/data/adults/train/man/aj/2a.spc $CLA_ROOT/memory/20150826_02.cla
ipython operate_cla.py $CLA_ROOT/corpus/tidigits_flac/data/adults/train/man/aj/2a.spc $CLA_ROOT/memory/20150826_02.cla
ipython operate_cla.py $CLA_ROOT/corpus/tidigits_flac/data/adults/train/man/aj/2a.spc $CLA_ROOT/memory/20150826_02.cla
ipython operate_cla.py $CLA_ROOT/corpus/tidigits_flac/data/adults/train/man/aj/2a.spc $CLA_ROOT/memory/20150826_02.cla
ipython operate_cla.py $CLA_ROOT/corpus/tidigits_flac/data/adults/train/man/aj/2a.spc $CLA_ROOT/memory/20150826_02.cla
ipython operate_cla.py $CLA_ROOT/corpus/tidigits_flac/data/adults/train/man/aj/2a.spc $CLA_ROOT/memory/20150826_02.cla
ipython operate_cla.py $CLA_ROOT/corpus/tidigits_flac/data/adults/train/man/aj/2a.spc $CLA_ROOT/memory/20150826_02.cla
ipython operate_cla.py $CLA_ROOT/corpus/tidigits_flac/data/adults/train/man/aj/2a.spc $CLA_ROOT/memory/20150826_02.cla
ipython operate_cla.py $CLA_ROOT/corpus/tidigits_flac/data/adults/train/man/aj/2a.spc $CLA_ROOT/memory/20150826_02.cla
ipython operate_cla.py $CLA_ROOT/corpus/tidigits_flac/data/adults/train/man/aj/2a.spc $CLA_ROOT/memory/20150826_02.cla
ipython operate_cla.py $CLA_ROOT/corpus/tidigits_flac/data/adults/train/man/aj/2a.spc $CLA_ROOT/memory/20150826_02.cla
ipython operate_cla.py $CLA_ROOT/corpus/tidigits_flac/data/adults/train/man/aj/2a.spc $CLA_ROOT/memory/20150826_02.cla
ipython operate_cla.py $CLA_ROOT/corpus/tidigits_flac/data/adults/train/man/aj/2a.spc $CLA_ROOT/memory/20150826_02.cla
ipython operate_cla.py $CLA_ROOT/corpus/tidigits_flac/data/adults/train/man/aj/2a.spc $CLA_ROOT/memory/20150826_02.cla
ipython operate_cla.py $CLA_ROOT/corpus/tidigits_flac/data/adults/train/man/aj/2a.spc $CLA_ROOT/memory/20150826_02.cla
ipython operate_cla.py $CLA_ROOT/corpus/tidigits_flac/data/adults/train/man/aj/2a.spc $CLA_ROOT/memory/20150826_02.cla
ipython operate_cla.py $CLA_ROOT/corpus/tidigits_flac/data/adults/train/man/aj/2a.spc $CLA_ROOT/memory/20150826_02.cla
ipython operate_cla.py $CLA_ROOT/corpus/tidigits_flac/data/adults/train/man/aj/2a.spc $CLA_ROOT/memory/20150826_02.cla
ipython operate_cla.py $CLA_ROOT/corpus/tidigits_flac/data/adults/train/man/aj/2a.spc $CLA_ROOT/memory/20150826_02.cla
ipython operate_cla.py $CLA_ROOT/corpus/tidigits_flac/data/adults/train/man/aj/2a.spc $CLA_ROOT/memory/20150826_02.cla
ipython operate_cla.py $CLA_ROOT/corpus/tidigits_flac/data/adults/train/man/aj/2a.spc $CLA_ROOT/memory/20150826_02.cla
ipython operate_cla.py $CLA_ROOT/corpus/tidigits_flac/data/adults/train/man/aj/2a.spc $CLA_ROOT/memory/20150826_02.cla
ipython operate_cla.py $CLA_ROOT/corpus/tidigits_flac/data/adults/train/man/aj/2a.spc $CLA_ROOT/memory/20150826_02.cla
ipython operate_cla.py $CLA_ROOT/corpus/tidigits_flac/data/adults/train/man/aj/2a.spc $CLA_ROOT/memory/20150826_02.cla
ipython operate_cla.py $CLA_ROOT/corpus/tidigits_flac/data/adults/train/man/aj/2a.spc $CLA_ROOT/memory/20150826_02.cla
ipython operate_cla.py $CLA_ROOT/corpus/tidigits_flac/data/adults/train/man/aj/2a.spc $CLA_ROOT/memory/20150826_02.cla
ipython operate_cla.py $CLA_ROOT/corpus/tidigits_flac/data/adults/train/man/aj/2a.spc $CLA_ROOT/memory/20150826_02.cla
ipython operate_cla.py $CLA_ROOT/corpus/tidigits_flac/data/adults/train/man/aj/2a.spc $CLA_ROOT/memory/20150826_02.cla
ipython operate_cla.py $CLA_ROOT/corpus/tidigits_flac/data/adults/train/man/aj/2a.spc $CLA_ROOT/memory/20150826_02.cla
ipython operate_cla.py $CLA_ROOT/corpus/tidigits_flac/data/adults/train/man/aj/2a.spc $CLA_ROOT/memory/20150826_02.cla
ipython operate_cla.py $CLA_ROOT/corpus/tidigits_flac/data/adults/train/man/aj/2a.spc $CLA_ROOT/memory/20150826_02.cla
ipython operate_cla.py $CLA_ROOT/corpus/tidigits_flac/data/adults/train/man/aj/2a.spc $CLA_ROOT/memory/20150826_02.cla
ipython operate_cla.py $CLA_ROOT/corpus/tidigits_flac/data/adults/train/man/aj/2a.spc $CLA_ROOT/memory/20150826_02.cla
ipython operate_cla.py $CLA_ROOT/corpus/tidigits_flac/data/adults/train/man/aj/2a.spc $CLA_ROOT/memory/20150826_02.cla
ipython operate_cla.py $CLA_ROOT/corpus/tidigits_flac/data/adults/train/man/aj/2a.spc $CLA_ROOT/memory/20150826_02.cla
ipython operate_cla.py $CLA_ROOT/corpus/tidigits_flac/data/adults/train/man/aj/2a.spc $CLA_ROOT/memory/20150826_02.cla
ipython operate_cla.py $CLA_ROOT/corpus/tidigits_flac/data/adults/train/man/aj/2a.spc $CLA_ROOT/memory/20150826_02.cla
ipython operate_cla.py $CLA_ROOT/corpus/tidigits_flac/data/adults/train/man/aj/2a.spc $CLA_ROOT/memory/20150826_02.cla
ipython operate_cla.py $CLA_ROOT/corpus/tidigits_flac/data/adults/train/man/aj/2a.spc $CLA_ROOT/memory/20150826_02.cla
ipython operate_cla.py $CLA_ROOT/corpus/tidigits_flac/data/adults/train/man/aj/2a.spc $CLA_ROOT/memory/20150826_02.cla
ipython operate_cla.py $CLA_ROOT/corpus/tidigits_flac/data/adults/train/man/aj/2a.spc $CLA_ROOT/memory/20150826_02.cla
ipython operate_cla.py $CLA_ROOT/corpus/tidigits_flac/data/adults/train/man/aj/2a.spc $CLA_ROOT/memory/20150826_02.cla
ipython operate_cla.py $CLA_ROOT/corpus/tidigits_flac/data/adults/train/man/aj/2a.spc $CLA_ROOT/memory/20150826_02.cla
ipython operate_cla.py $CLA_ROOT/corpus/tidigits_flac/data/adults/train/man/aj/2a.spc $CLA_ROOT/memory/20150826_02.cla
ipython operate_cla.py $CLA_ROOT/corpus/tidigits_flac/data/adults/train/man/aj/2a.spc $CLA_ROOT/memory/20150826_02.cla
ipython operate_cla.py $CLA_ROOT/corpus/tidigits_flac/data/adults/train/man/aj/2a.spc $CLA_ROOT/memory/20150826_02.cla
ipython operate_cla.py $CLA_ROOT/corpus/tidigits_flac/data/adults/train/man/aj/2a.spc $CLA_ROOT/memory/20150826_02.cla
ipython operate_cla.py $CLA_ROOT/corpus/tidigits_flac/data/adults/train/man/aj/2a.spc $CLA_ROOT/memory/20150826_02.cla
ipython operate_cla.py $CLA_ROOT/corpus/tidigits_flac/data/adults/train/man/aj/2a.spc $CLA_ROOT/memory/20150826_02.cla
ipython operate_cla.py $CLA_ROOT/corpus/tidigits_flac/data/adults/train/man/aj/2a.spc $CLA_ROOT/memory/20150826_02.cla
ipython operate_cla.py $CLA_ROOT/corpus/tidigits_flac/data/adults/train/man/aj/2a.spc $CLA_ROOT/memory/20150826_02.cla
ipython operate_cla.py $CLA_ROOT/corpus/tidigits_flac/data/adults/train/man/aj/2a.spc $CLA_ROOT/memory/20150826_02.cla
ipython operate_cla.py $CLA_ROOT/corpus/tidigits_flac/data/adults/train/man/aj/2a.spc $CLA_ROOT/memory/20150826_02.cla
ipython operate_cla.py $CLA_ROOT/corpus/tidigits_flac/data/adults/train/man/aj/2a.spc $CLA_ROOT/memory/20150826_02.cla
ipython operate_cla.py $CLA_ROOT/corpus/tidigits_flac/data/adults/train/man/aj/2a.spc $CLA_ROOT/memory/20150826_02.cla
ipython operate_cla.py $CLA_ROOT/corpus/tidigits_flac/data/adults/train/man/aj/2a.spc $CLA_ROOT/memory/20150826_02.cla
ipython operate_cla.py $CLA_ROOT/corpus/tidigits_flac/data/adults/train/man/aj/2a.spc $CLA_ROOT/memory/20150826_02.cla
ipython operate_cla.py $CLA_ROOT/corpus/tidigits_flac/data/adults/train/man/aj/2a.spc $CLA_ROOT/memory/20150826_02.cla
ipython operate_cla.py $CLA_ROOT/corpus/tidigits_flac/data/adults/train/man/aj/2a.spc $CLA_ROOT/memory/20150826_02.cla
ipython operate_cla.py $CLA_ROOT/corpus/tidigits_flac/data/adults/train/man/aj/2a.spc $CLA_ROOT/memory/20150826_02.cla
ipython operate_cla.py $CLA_ROOT/corpus/tidigits_flac/data/adults/train/man/aj/2a.spc $CLA_ROOT/memory/20150826_02.cla
ipython operate_cla.py $CLA_ROOT/corpus/tidigits_flac/data/adults/train/man/aj/2a.spc $CLA_ROOT/memory/20150826_02.cla
ipython operate_cla.py $CLA_ROOT/corpus/tidigits_flac/data/adults/train/man/aj/2a.spc $CLA_ROOT/memory/20150826_02.cla
ipython operate_cla.py $CLA_ROOT/corpus/tidigits_flac/data/adults/train/man/aj/2a.spc $CLA_ROOT/memory/20150826_02.cla
ipython operate_cla.py $CLA_ROOT/corpus/tidigits_flac/data/adults/train/man/aj/2a.spc $CLA_ROOT/memory/20150826_02.cla
ipython operate_cla.py $CLA_ROOT/corpus/tidigits_flac/data/adults/train/man/aj/2a.spc $CLA_ROOT/memory/20150826_02.cla
ipython operate_cla.py $CLA_ROOT/corpus/tidigits_flac/data/adults/train/man/aj/2a.spc $CLA_ROOT/memory/20150826_02.cla
ipython operate_cla.py $CLA_ROOT/corpus/tidigits_flac/data/adults/train/man/aj/2a.spc $CLA_ROOT/memory/20150826_02.cla
ipython operate_cla.py $CLA_ROOT/corpus/tidigits_flac/data/adults/train/man/aj/2a.spc $CLA_ROOT/memory/20150826_02.cla
ipython operate_cla.py $CLA_ROOT/corpus/tidigits_flac/data/adults/train/man/aj/2a.spc $CLA_ROOT/memory/20150826_02.cla
ipython operate_cla.py $CLA_ROOT/corpus/tidigits_flac/data/adults/train/man/aj/2a.spc $CLA_ROOT/memory/20150826_02.cla
ipython operate_cla.py $CLA_ROOT/corpus/tidigits_flac/data/adults/train/man/aj/2a.spc $CLA_ROOT/memory/20150826_02.cla
ipython operate_cla.py $CLA_ROOT/corpus/tidigits_flac/data/adults/train/man/aj/2a.spc $CLA_ROOT/memory/20150826_02.cla
ipython operate_cla.py $CLA_ROOT/corpus/tidigits_flac/data/adults/train/man/aj/2a.spc $CLA_ROOT/memory/20150826_02.cla
ipython operate_cla.py $CLA_ROOT/corpus/tidigits_flac/data/adults/train/man/aj/2a.spc $CLA_ROOT/memory/20150826_02.cla
ipython operate_cla.py $CLA_ROOT/corpus/tidigits_flac/data/adults/train/man/aj/2a.spc $CLA_ROOT/memory/20150826_02.cla
ipython operate_cla.py $CLA_ROOT/corpus/tidigits_flac/data/adults/train/man/aj/2a.spc $CLA_ROOT/memory/20150826_02.cla
ipython operate_cla.py $CLA_ROOT/corpus/tidigits_flac/data/adults/train/man/aj/2a.spc $CLA_ROOT/memory/20150826_02.cla
ipython operate_cla.py $CLA_ROOT/corpus/tidigits_flac/data/adults/train/man/aj/2a.spc $CLA_ROOT/memory/20150826_02.cla